Setup and loop must be after declaration
Compile errors because setup and loop are at the start. 

src\main.cpp: In function 'void setup()':
src\main.cpp:84:16: error: 'testdrawline' was not declared in this scope
   testdrawline();      // Draw many lines
                ^
src\main.cpp:86:16: error: 'testdrawrect' was not declared in this scope
   testdrawrect();      // Draw rectangles (outlines)
                ^
src\main.cpp:88:16: error: 'testfillrect' was not declared in this scope
   testfillrect();      // Draw rectangles (filled)
                ^
src\main.cpp:90:18: error: 'testdrawcircle' was not declared in this scope
   testdrawcircle();    // Draw circles (outlines)
                  ^
src\main.cpp:92:18: error: 'testfillcircle' was not declared in this scope
   testfillcircle();    // Draw circles (filled)
                  ^
src\main.cpp:94:21: error: 'testdrawroundrect' was not declared in this scope
   testdrawroundrect(); // Draw rounded rectangles (outlines)
                     ^
src\main.cpp:96:21: error: 'testfillroundrect' was not declared in this scope
   testfillroundrect(); // Draw rounded rectangles (filled)
                     ^
src\main.cpp:98:20: error: 'testdrawtriangle' was not declared in this scope
   testdrawtriangle();  // Draw triangles (outlines)
                    ^
src\main.cpp:100:20: error: 'testfilltriangle' was not declared in this scope
   testfilltriangle();  // Draw triangles (filled)
                    ^
src\main.cpp:102:16: error: 'testdrawchar' was not declared in this scope
   testdrawchar();      // Draw characters of the default font
                ^
src\main.cpp:104:18: error: 'testdrawstyles' was not declared in this scope
   testdrawstyles();    // Draw 'stylized' characters
                  ^
src\main.cpp:106:18: error: 'testscrolltext' was not declared in this scope
   testscrolltext();    // Draw scrolling text
                  ^
src\main.cpp:108:18: error: 'testdrawbitmap' was not declared in this scope
   testdrawbitmap();    // Draw a small bitmap image
                  ^
src\main.cpp:116:48: error: 'testanimate' was not declared in this scope
   testanimate(logo_bmp, LOGO_WIDTH, LOGO_HEIGHT); // Animate bitmaps
                                                ^
*** [.pio\build\esp32doit-devkit-v1\src\main.cpp.o] Error 1